[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TechAndStuff"
authors = [{name = "CleverUser123", email = "CleverUser12345@gmail.com"}]
dynamic = ["version", "description"]
